GAME_WIDTH_PX = 1024
GAME_HEIGHT_PX = 720
GAME_FPS = 120
GAME_NAME = "Pygame Template"
SAVE_FOLDER_NAME = "mygame"

MINIMUM_ASTEROID_SIZE = 25
MAXIMUM_ASTEROID_SIZE = 120
MINIMUM_ASTEROID_VERTICES = 8
MAXIMUM_ASTEROID_VERTICES = 20
ASTEROID_VARIANCE = 0.25
